### ISSUE TITLE
Generate get methods

### ISSUE THREAD

**Issue by elhoo** [gejun123456/intellij-generateAllSetMethod#15]
Please also consider generating get methods.

Use case: I have a class with >30 fields (don't ask..) and I want to write a unit test that verify stuff. To do that I will write 
`
assertThat(myObject.getXXXX()).isEqualTo(...);
`
It would help a lot if I could generate all get calls. Then the next step would simple to "column selection mode" and add 'assertThat( ).isEqualTo()' around them.

**Comment by gejun123456** [comment]
cool, will try to support it.

**Comment by Loki-Afro** [comment]
would absolutely love to see that!

**Comment by jackzhangyk** [comment]
is this feature has been supported?

**Comment by gejun123456** [comment]
I will look into it this weekend

**Comment by gejun123456** [comment]
2.2 supported.
