### ISSUE TITLE
Add selector for disabling default values for setters

### ISSUE THREAD

**Issue by kaos-169** [gejun123456/intellij-generateAllSetMethod#22]
Adding any default values in setters may lead to error when programmer forget replace value in one of setters. Instead it would be useful to generate setters without values. All of this setters will be highlighted as error while it not filled - wonderful anti error indicator.

**Comment by gejun123456** [comment]
let me think about it. i could make it as an option to config.

**Comment by gejun123456** [comment]
thanks for your advice.

**Comment by kaos-169** [comment]
@gejun123456 thank you for your plugin. It must be a vanilla intellij code generation feature, not external plugin.

**Comment by gejun123456** [comment]
2.2 supported.
