### ISSUE TITLE
about 'generate List Set Map return value' use guava

### ISSUE THREAD

**Issue by ralphhuang** [gejun123456/intellij-generateAllSetMethod#25]
the code generate via 'generate List Set Map return value' now using guava framework,can support via 
standard jdk collection?

**Comment by gejun123456** [comment]
this is already supported, i have tested it few minutes ago, it works fine.

**Comment by ralphhuang** [comment]
ok,tks!
in fact,the plugin prefer to use guava initialize default value,if guava exist in project.
