### ISSUE TITLE
请问idea 的mac快捷键是什么

### ISSUE THREAD

**Issue by jianpei-liu** [gejun123456/intellij-generateAllSetMethod#29]

**Comment by gejun123456** [comment]
command+enter

**Comment by Shaun-Yao** [comment]
@gejun123456  mac idea 2018.2 , GenerateAllSetter 2.0 如何使用？alt+enter, cmd+enter 快捷键都不是

**Comment by gejun123456** [comment]
好的，我看看

**Comment by gejun123456** [comment]
alt+enter 我昨天试了2018.2的版本，没发现问题的，如果有问题的话 请发个截图看看

**Comment by Shaun-Yao** [comment]
sorry, 我之前测试的不对，现在可以了，谢谢！

**Comment by yskyto** [comment]
idea 2018.2 重启一下电脑 突然不能使用了.
