### ISSUE TITLE
Small request on the naming..

### ISSUE THREAD

**Issue by RListerberg** [gejun123456/intellij-generateAllSetMethod#31]
Hi there, is it possible to fix the "generate all setter" to "Generate all setters"

![generateallsetters](https://user-images.githubusercontent.com/16943357/47569297-89027800-d933-11e8-8216-9c2f3d2a120e.PNG)

Sorry for my small OCD problem, absolutely love the plugin

**Comment by gejun123456** [comment]
No problem. Thanks for pointing out.

**Comment by gejun123456** [comment]
22fca581b1e5065367d13452eea99967642eb7de  will publish it in several days

**Comment by gejun123456** [comment]
fixed  you can install it via https://github.com/gejun123456/intellij-generateAllSetMethod/files/2663980/GenerateAllSetter-2.1.zip
