### ISSUE TITLE
Formatting

### ISSUE THREAD

**Issue by DJakosa** [gejun123456/intellij-generateAllSetMethod#33]
Hi. This is a convenient plugin. I am pointing issue with generated code.

For example, generated line for class `Foo` would be

`Foo name= new Foo()` instead of 

`Foo name = Foo()`. It's missing a space before `=`.

I reckon that the problem is [here](https://github.com/gejun123456/intellij-generateAllSetMethod/blob/master/src/main/java/com/bruce/intellijplugin/generatesetter/actions/GenerateAllSetterAction.java#L224).

Fix would really save additional step of manual formatting or hitting shortcut for formatter.

**Comment by gejun123456** [comment]
Thanks for pointing out, i will fix it.

**Comment by gejun123456** [comment]
fixed, you can install it via  https://github.com/gejun123456/intellij-generateAllSetMethod/files/2663980/GenerateAllSetter-2.1.zip
