### ISSUE TITLE
Why somebody use IDEA 3.5 but can't apply getter to setter ?

### ISSUE THREAD

**Issue by cy1ng** [gejun123456/intellij-generateAllSetMethod#35]
![image](https://user-images.githubusercontent.com/12083893/54731871-aaf2e480-4bcb-11e9-9513-5d241c1fc4d7.png)

**Comment by cy1ng** [comment]
this dialog can't show "genAllSetter" when I select return type "BlackInfo" in image above !  Please give me a  hand! thanks!

**Comment by gejun123456** [comment]
Is there any set method in BlackInfo entity?

**Comment by cy1ng** [comment]
yes

**Comment by cy1ng** [comment]
@gejun123456  I'am sure that  It has set method !

**Comment by gejun123456** [comment]
There is a bug in it. I will fix it. Thanks

**Comment by gejun123456** [comment]
already fixed, can download 2.4 at https://plugins.jetbrains.com/plugin/9360-generateallsetter
