### ISSUE TITLE
not available on return types of methods in 

### ISSUE THREAD

**Issue by mpl1979** [gejun123456/intellij-generateAllSetMethod#36]
Problem seen in 2.3 (I think it worked in 2.1)
If I have a new method:
```
private SubscriptionFile convertFromFile(final File file) {
        return null;
    }
```
where File and SubscriptionFile has the same members.
I used to be able to place the cursor on return type and get the "generate all setters" context option . The result would be:
```
private SubscriptionFile convertFromFile(final File file) {
        SubscriptionFile subscriptionFile = new SubscriptionFile();
        subscriptionFile.setX(file.getX());
        subscriptionFile.setY(file.getY());
        subscriptionFile.setZ(file.getZ());
        return subscriptionFile;
        return null;
    }
```
Where I have to remove the return null; line
I particularly liked the automatic matching of the setter and getter methods.

But this no longer works. Is it supposed to?

**Comment by gejun123456** [comment]
Seems to have a bug in 2.3, will fix it

**Comment by gejun123456** [comment]
fixed, can download at https://plugins.jetbrains.com/plugin/9360-generateallsetter

**Comment by mpl1979** [comment]
That was fast :). Thank you
