### ISSUE TITLE
作者，我根据工作中的使用对插件有些改进想法，并愿意参与开发

### ISSUE THREAD

**Issue by xczs666** [gejun123456/intellij-generateAllSetMethod#48]
昨天把代码拉下来后已经编译通过，目前完成了无参数使用`this`来赋值的逻辑，也就是支持构造方法。后续想要改进：
1. 在变量上触发赋值时也根据入参+this来尝试赋值（我在业务开发中有太多中间类的转换了）
2. 多参数入参及`this`属性遍历查找相似的赋值
3. 支持Lombok Builder（只考虑支持Lombok的Builder格式，Builder模式变种太多而目前基本lombok一统江山了）
4. 名字匹配不要求字符串完全一致，而是使用去除非字母符号然后字符串转为小写来匹配

想请问作者有什么功能是考虑接受的吗？有的话可以一起沟通，刚刚尝试写插件，很多类不熟悉，可以请教下大佬，我也可以贡献一定代码。

**Comment by gejun123456** [comment]
1,2 不太懂，有例子看下么， 3,4 可以弄的。 谢谢建议

**Comment by xczs666** [comment]
1,2其实是一个意思。比如
```java
public class Animal {
    private String name;
}
public class IdCard {
    private String id;
}
public class Person {
    private String id;
    private String name;

    public Animal create() {
        Animal animal = new Animal();
        animal.setName(**this.**getName());
        return animal;
    }
    public Person create(Animal animal, IdCard card) {
        Person person = new Person();
        person.setName(animal.getName());
        person.setId(card.getId())
        return animal;
    }
}
```
就是遍历入参+this为要返回的对象域赋值。
另外我看了你到源码，感觉要改的话架构不太兼容，代码会很乱，另外使用<intentionAction>来扩展intellij的基本功能，会有非常多的冗余调用，我想用<action>的方式自己撸一个了。

**Comment by mrdear** [comment]
> 1,2其实是一个意思。比如
> 
> ```java
> public class Animal {
>     private String name;
> }
> public class IdCard {
>     private String id;
> }
> public class Person {
>     private String id;
>     private String name;
> 
>     public Animal create() {
>         Animal animal = new Animal();
>         animal.setName(this.getName());
>         return animal;
>     }
>     public Person create(Animal animal, IdCard card) {
>         Person person = new Person();
>         person.setName(animal.getName());
>         person.setId(card.getId())
>         return animal;
>     }
> }
> ```
> 
> 就是遍历入参+this为要返回的对象域赋值。
> 另外我看了你到源码，感觉要改的话架构不太兼容，代码会很乱，另外使用`<intentionAction>`来扩展intellij的基本功能，会有非常多的冗余调用，我想用`<action>`的方式自己撸一个了。

有开发计划了吗？这个功能确实挺好的。

**Comment by xczs666** [comment]
> > 1,2其实是一个意思。比如
> > ```java
> > public class Animal {
> >     private String name;
> > }
> > public class IdCard {
> >     private String id;
> > }
> > public class Person {
> >     private String id;
> >     private String name;
> > 
> >     public Animal create() {
> >         Animal animal = new Animal();
> >         animal.setName(this.getName());
> >         return animal;
> >     }
> >     public Person create(Animal animal, IdCard card) {
> >         Person person = new Person();
> >         person.setName(animal.getName());
> >         person.setId(card.getId())
> >         return animal;
> >     }
> > }
> > ```
> > 
> > 
> > 就是遍历入参+this为要返回的对象域赋值。
> > 另外我看了你到源码，感觉要改的话架构不太兼容，代码会很乱，另外使用`<intentionAction>`来扩展intellij的基本功能，会有非常多的冗余调用，我想用`<action>`的方式自己撸一个了。
> 
> 有开发计划了吗？这个功能确实挺好的。

已经根据我的需求开发完了，细节没有仔细雕琢，功能ok。SetterFieldHelper你可以搜下
