### ISSUE TITLE
IDEA2020上有id属性会有两次setId()

### ISSUE THREAD

**Issue by Gui052** [gejun123456/intellij-generateAllSetMethod#53]
如果一个DO对象有id属性，则会有两次DO.setId()

**Comment by gejun123456** [comment]
ok, 我看看

**Comment by Gui052** [comment]
我看了一下，是我的DO继承了一个抽象类，里面有一个id属性是个泛型，应该是这样才会出现的两次setId，两次的默认值是不一样的。插件很好用，是我的问题哈哈，尴尬
