### ISSUE TITLE
I don't know how to use 'Generate setter getter converter'

### ISSUE THREAD

**Issue by kimdy003** [gejun123456/intellij-generateAllSetMethod#79]
I don't know how to use 'Generate setter getter converter'
Please tell me how to use 'Generate setter getter converter'

The getter is not created in () when using'Generate setter getter converter'
![image](https://user-images.githubusercontent.com/31909322/186658844-e3377a86-0f44-4a08-8c22-839f2ef92e0d.png)

I need a photo or gif file of the solution

**Comment by gejun123456** [comment]
https://raw.githubusercontent.com/gejun123456/intellij-generateAllSetMethod/master/screenshot/generate_the_conveter.gif

**Comment by kimdy003** [comment]
Thank you!
