### ISSUE TITLE
2022.3插件不生效

### ISSUE THREAD

**Issue by licocon** [gejun123456/intellij-generateAllSetMethod#87]
macos option+enter 不生效了，。前几天没更新好像还是好用的
<img width="1380" alt="iShot_2022-12-02_11 01 44" src="https://user-images.githubusercontent.com/36863277/205205653-a8f1e637-deb2-45b1-b7fa-10af6614ea44.png">

**Comment by imldy** [comment]
2022.3.1 +1 
intention Actions 不显示选项

**Comment by imldy** [comment]
手动拖GenerateAllSetter-2.8.2.zip到IDEA，重启后发现不行，但是后续不知为何又可以了。不确定跟手动安装有没有关系。
