### ISSUE TITLE
mac 没有提示生成setter

### ISSUE THREAD

**Issue by deipss** [gejun123456/intellij-generateAllSetMethod#91]
**idea版本=IntelliJ IDEA 2023.1.1 (Community Edition)
mac=13.2.1 (22D68)**
option+enter键，没有generator setter 的提示

<img width="934" alt="image" src="https://github.com/gejun123456/intellij-generateAllSetMethod/assets/9259745/5957e77f-e40c-46b5-89f3-29f41a10f893">

**Comment by Nnaking** [comment]
同，我还以为被卸载了

**Comment by deipss** [comment]
> 类上有`@Data`注解吗，在没有`@Data`注解或者Get Set方法就不会有提示。

是的，加上@Data后，就可以了。
